version: '3'

services:

  miniserve:
    image: svenstaro/miniserve@sha256:567dbf7300d1960267ccc761e90ecc7e7d15377017e26caeb88b1f30d8be5fa5
    command: /public
    volumes:
      - /var/volumes/syncthing/public:/public:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public-files.rule=Host(`public.rknt.de`)"
      - "traefik.http.routers.public-files.entrypoints=websecure"
      - "traefik.http.routers.public-files.tls.certresolver=myresolver"
      - "traefik.http.services.public-files.loadbalancer.server.port=8080"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
