version: '3'

services:

  miniserve:
    image: svenstaro/miniserve@sha256:41d81b005bcc0b06da8167f897660454a6bdb3ab57fe3d8a82dc1455bf9a9b2d
    command: /public
    volumes:
      - /var/volumes/syncthing/public:/public:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public-files.rule=Host(`public.rknt.de`)"
      - "traefik.http.routers.public-files.entrypoints=websecure"
      - "traefik.http.routers.public-files.tls.certresolver=myresolver"
      - "traefik.http.services.public-files.loadbalancer.server.port=8080"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
