version: '3'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf@sha256:581d68b2a6fc7ebf58d81c878a9f387cbbc0d88ac9d37b298b9cee10168af85b
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
      - TZ=Europe/London
    volumes:
      - /var/volumes/airsonic/music:/audiobooks
      - /var/volumes/audiobookshelf/config:/config
      - /var/volumes/audiobookshelf/metadata:/metadata
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.audiobooks.rule=Host(`audiobooks.rknt.de`)"
      - "traefik.http.routers.audiobooks.entrypoints=websecure"
      - "traefik.http.routers.audiobooks.tls.certresolver=myresolver"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
