version: '3'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf@sha256:91564c31204f09b2a9be63e4d3a4d553087df775ece6c99dcd931b3c4a0ff951
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
      - TZ=Europe/London
    volumes:
      - /var/volumes/airsonic/music:/audiobooks
      - /var/volumes/audiobookshelf/config:/config
      - /var/volumes/audiobookshelf/metadata:/metadata
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.audiobooks.rule=Host(`audiobooks.rknt.de`)"
      - "traefik.http.routers.audiobooks.entrypoints=websecure"
      - "traefik.http.routers.audiobooks.tls.certresolver=myresolver"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
