version: '3'

services:
  calibre:
    image: linuxserver/calibre-web@sha256:36cc48075aceef6f919554c359ffd4caefb9aa5613e12da6ec0a45fea847293c
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/volumes/calibre-web:/config
      - /var/volumes/syncthing/Calibre-Library:/books:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre-web.rule=Host(`books.rknt.de`)"
      - "traefik.http.routers.calibre-web.entrypoints=websecure"
      - "traefik.http.routers.calibre-web.tls.certresolver=myresolver"
    restart: unless-stopped

networks:
  traefik:
    external: true
