version: '3'

services:
  calibre:
    image: linuxserver/calibre-web@sha256:c2b9bafa3aa1907af5b4a1a5780fc0d646cbaad959c39c316906874ea062b512
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/volumes/calibre-web:/config
      - /var/volumes/syncthing/Calibre-Library:/books:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre-web.rule=Host(`books.rknt.de`)"
      - "traefik.http.routers.calibre-web.entrypoints=websecure"
      - "traefik.http.routers.calibre-web.tls.certresolver=myresolver"
    restart: unless-stopped

networks:
  traefik:
    external: true
