version: '3'
services:
  syncthing:
    image: syncthing/syncthing@sha256:4a961394ca471f4e48f31ad2cef50697e502c8799e2e98477a1c3844e0c5bc54
    container_name: syncthing
    hostname: rknt.de
    environment:
      - PUID=1000
      - PGID=1002
    volumes:
      - /var/volumes/syncthing:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`sync.rknt.de`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls.certresolver=myresolver"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
